# Generated by Django 3.1.7 on 2022-04-27 01:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0006_auto_20220403_2338'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000)),
                ('categories', models.CharField(max_length=2000)),
                ('article_url', models.FileField(null=True, upload_to='articles')),
                ('date_of_creation', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('accepted_to_published_by_researchers', models.BooleanField(default=False)),
                ('last_modification', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(blank=True, default='pending', max_length=30)),
                ('conference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.conference')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article_Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepte_to_publish_article', models.BooleanField(default=False)),
                ('article', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
    ]
