# Generated by Django 3.1.7 on 2022-04-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_url',
            field=models.FileField(null=True, upload_to='articles'),
        ),
    ]
