# Generated by Django 3.1.7 on 2022-04-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_author_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(through='articles.Article_Author', to='articles.Author'),
        ),
    ]
