# Generated by Django 3.1.7 on 2022-04-04 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220404_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_url',
        ),
    ]
