# Generated by Django 3.1.7 on 2022-04-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_reviewers'),
        ('articles', '0002_auto_20220426_1802'),
    ]

    operations = [
    ]
