# Generated by Django 3.1.7 on 2022-05-12 13:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_merge_20220429_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, default='waiting for authors', max_length=30),
        ),
        migrations.CreateModel(
            name='ArticleStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_modification', models.DateTimeField(default=datetime.datetime.now, editable=False, max_length=100)),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.article')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.articlestatus')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleDatesHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_modification', models.DateTimeField(default=datetime.datetime.now, editable=False, max_length=100)),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.article')),
            ],
        ),
    ]
