# Generated by Django 3.1.7 on 2022-03-30 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=3000)),
                ('categories', models.CharField(max_length=500)),
                ('name_of_host', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(max_length=100)),
                ('end_date', models.DateTimeField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='logos')),
                ('is_accepted', models.BooleanField(default=False)),
                ('accepted_personnes', models.ManyToManyField(related_name='conference_accepted_personnes', to=settings.AUTH_USER_MODEL)),
                ('applied_personnes', models.ManyToManyField(related_name='conference_applied_personnes', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='conference_creator', to=settings.AUTH_USER_MODEL)),
                ('reviewers', models.ManyToManyField(related_name='conference_reviewers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
