# Generated by Django 3.1.7 on 2022-03-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
