# Generated by Django 3.1.7 on 2022-04-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_auto_20220331_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('refused', 'refused')], default='waiting', max_length=15),
        ),
    ]
