# Generated by Django 3.1.7 on 2022-04-03 19:24

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conferences', '0004_auto_20220402_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ['-date_of_creation']},
        ),
        migrations.RemoveField(
            model_name='conference',
            name='accepted_personnes',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='applied_personnes',
        ),
        migrations.AddField(
            model_name='conference',
            name='accepted_articles',
            field=models.ManyToManyField(related_name='conference_accepted_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conference',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='conference',
            name='pending_articles',
            field=models.ManyToManyField(related_name='conference_pending_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
