# Generated by Django 3.1.7 on 2022-04-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_auto_20220403_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('refused', 'refused')], default='pending', max_length=15),
        ),
    ]
