# Generated by Django 3.1.7 on 2022-05-12 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0008_auto_20220512_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencedateshistory',
            name='date_of_modification',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='confernecestatushistory',
            name='date_of_modification',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, max_length=100),
        ),
    ]
