# Generated by Django 3.1.7 on 2022-05-09 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_submition',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 13, 57, 47, 369974), editable=False, max_length=100),
        ),
    ]
