# Generated by Django 3.1.7 on 2022-05-12 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20220509_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_submition',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 1, 43, 43, 357419), editable=False, max_length=100),
        ),
    ]
