# Generated by Django 3.1.7 on 2022-05-12 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20220512_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_submition',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 12, 35, 3, 850964), editable=False, max_length=100),
        ),
    ]
