# Generated by Django 3.1.7 on 2022-05-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20220512_1409'),
        ('reports', '0003_auto_20220510_1127'),
    ]

    operations = [
    ]
