# Generated by Django 3.1.7 on 2022-05-16 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20220513_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_submition',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 14, 22, 41, 237866), editable=False, max_length=100),
        ),
    ]
