# Generated by Django 3.1.7 on 2022-05-27 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_merge_20220513_1704'),
        ('reports', '0011_auto_20220516_1422'),
    ]

    operations = [
    ]
