# Generated by Django 3.1.7 on 2022-05-27 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_merge_20220527_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_submition',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 2, 27, 40, 934298), editable=False, max_length=100),
        ),
    ]
