# Generated by Django 3.1.7 on 2022-05-27 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20220527_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_submition',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 13, 46, 32, 443976), editable=False, max_length=100),
        ),
    ]
