# Generated by Django 3.1.7 on 2022-06-17 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20220527_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_submition',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 16, 10, 52, 906111), editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='score',
            field=models.FloatField(max_length=3000),
        ),
    ]
