# Generated by Django 3.1.7 on 2022-03-31 14:34

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('date_of_creation', models.CharField(default=datetime.datetime.now, max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('invitation_status', models.CharField(blank=True, max_length=30, null=True)),
                ('conference_id', models.PositiveIntegerField()),
                ('request_to_edit_article_id', models.CharField(blank=True, max_length=100, null=True)),
                ('users_list', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
