# Generated by Django 3.1.7 on 2022-03-31 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notification',
        ),
    ]
