# Generated by Django 3.1.7 on 2022-04-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='invitation_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('accepted', 'accepted'), ('refused', 'refused')], default='pending', max_length=30, null=True),
        ),
    ]
