# Generated by Django 3.1.7 on 2022-04-03 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20220402_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_of_creation']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, max_length=100),
        ),
    ]
