# Generated by Django 3.1.7 on 2022-05-27 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0005_auto_20220403_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='users_list',
        ),
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
