# Generated by Django 3.1.7 on 2022-05-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20220527_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='conference_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
